// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sycpmhvfcqlrgclybihv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5Y3BtaHZmY3FscmdjbHliaWh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM2OTQ1NzQsImV4cCI6MjA0OTI3MDU3NH0.7RdYc8gVJTyZ0n9qBL1n9yVBSOFqLIZrbbOX6m-Qmh0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);